services:
  exonym-example-sso:
    container_name: exonym-example-sso
    build:
      context: .
      dockerfile: Dockerfile
    image: exonym-example-sso:latest
    ports: 
      - 20001:8080
    env_file:
      - envfile.env
    environment:
     - HTTPS_METHOD=noredirect
     - VIRTUAL_HOST=localhost
     - VIRTUAL_PORT=20001
    volumes:
      - ~/github/exonymwallet/io.exonym.example.sso/tokens:/var/www/html/tokens
    networks:
      - net0


networks:
 net0:
  name: net0
